spring:
  profiles:
    active: local

  # datasource:
  #   url: jdbc:mysql://localhost:3306/quddy
  #   username: root
  #   password: root
  #   driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
